### ISSUE TITLE
Replace PDoc3 with MKDocs or Portray

### ISSUE THREAD

**Issue by KyleKing** [KyleKing/calcipy#25]
## Tasks

- [X] Try [timothycrosley/portray](https://github.com/timothycrosley/portray) (may be the simplest because it works out of the box)
    - Will want to revisit when Google docstrings are supported, see: https://github.com/timothycrosley/portray/issues/47
- [X] Checkout how to release to Github using MKDocs {Implemented with [recipes](https://github.com/KyleKing/recipes/blob/main/recipes/tasks.py#L37)}
- [X] Example Projects
    - ~https://github.com/smarie/python-autoclass/tree/master/docs~
    - ~https://github.com/smarie/python-pyfields/tree/master/docs~
    - ~https://smarie.github.io/python-pyfields/api_reference/~
    - https://pawamoy.github.io/mkdocstrings
- [X] Try [pawamoy/mkdocstrings](https://github.com/pawamoy/mkdocstrings)
    - https://pawamoy.github.io/mkdocstrings/handlers/python/

---

Old notes from #18:

Also, transition to MkDocs from PDoc3. See an example project: https://github.com/smarie/python-autoclass/tree/master/docs and the documentation for auto-generated API docs: https://pawamoy.github.io/mkdocstrings/handlers/python/. Will need the docstrings package: https://github.com/pawamoy/mkdocstrings

MKDocs can be hosted on RTD if I ever wanted a hosted option: https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html

I don't need the hacks for making an `__init__.py` with the README and converting the scripts/tests to `0<folder>` dosctring code. They can just be moved to Markdown!
