### ISSUE TITLE
Add static code visualization tools

### ISSUE THREAD

**Issue by KyleKing** [KyleKing/calcipy#31]
Update: I experimented with several of these tools as part of the Design Patterns Adventure Game. Source code here: https://github.com/DesignPatternsAdventure/pattern_feedback_tool/blob/cf4923683041fc268c527eaaf49f7072cdea8ee6/pattern_feedback_tool/graphics.py

Experiment with and implement tools to create code diagrams

- [x] [xdot.py](https://github.com/jrfonseca/xdot.py) Viewer for dot-language files (https://github.com/jrfonseca/xdot.py/issues/110)
- [x] Maybe something that shows method calls and a sequence diagram from static analysis?
	- [x] Old Variations of PyCallGraph
        - ~~[pycallgraph3](https://pypi.org/project/pycallgraph3/)~~
    	- ~~[pycallgraph5](https://pypi.org/project/pycallgraph5/)~~ -- Only a single release in 2021
	    - ~~[callgraph4py](https://pypi.org/project/callgraph4py/)~~ -- Only a single 
release in 2021
	- [x] [code2flow](https://github.com/scottrogowski/code2flow): Pretty good call graphs for dynamic languages
		- Example: `pipx install code2flow && code2flow calcipy/*.py calcipy/*/*.py && open out.png`
	- [ ] [pycg](https://github.com/vitsalis/pycg):  Static Python call graph generator (which could be useful for extracting call graph information to build tools on top of)
	- [x] [pyan](https://github.com/Technologicat/pyan) (2021)
- [x] A package that generates PlantUML class diagrams
    - [x] pylint - pyreverse (implemented)
    - [x] [pydeps](https://github.com/thebjorn/pydeps): displays imports (Actively developed)
    - [x] ~~py-puml (contains py2puml?)~~ https://github.com/deadbok/py-puml-tools (2017)
    - [x] py2puml: https://github.com/lucsorel/py2puml (Generates PlantUML for class diagrams)
    - [x] Show PlantUML images in docs: https://github.com/christo-ph/mkdocs_build_plantuml
	    - [x] Or show inline diagrams with: https://github.com/mikitex70/plantuml-markdown
- [x] Checout [pawamoy/python-static-code-analysis-tools](https://pawamoy.github.io/posts/python-static-code-analysis-tools/)
    - [x] [pyflakes](https://pypi.org/project/pyflakes/) (old)
    - [x] [pydocstyles](https://pypi.org/project/pydocstyle/)
    - [x] [pyroma](https://pypi.org/project/pyroma/)
    - [x] [dodgy](https://pypi.org/project/dodgy/) (old - 2019)
- [x] And [analysis-tools-dev/static-analysis](https://github.com/analysis-tools-dev/static-analysis#python)
    - [x] [xenon](https://github.com/rubik/xenon) - runs radon
- [ ] [AppMap](https://pypi.org/project/appmap) (See snippets below - requires dynamic recording, but can provide more concrete information)
    - https://github.com/applandinc/vscode-appland/blob/master/doc/TUTORIAL-PYTHON-CHIPYORG.md
    - https://appland.com/company/view-demos.html
    - The VSCode integration shines when working with Web Apps

---

```yaml
# https://pypi.org/project/appmap/
name: package
packages:
- path: package
  shallow: false
```

```sh
set APPMAP=true
set APPMAP_OUTPUT_DIR=C:/Users/king.kyle/Developer/Projects/mapas_utilization_tracker
set APPMAP_LOG_LEVEL=info

poetry run doit run test
pytest -svv
# But not running the tests...?
```

---

```py
# TODO: Show call chain in dash_charts: https://github.com/vmdesenvolvimento/pycallgraph3
# See below attached file for more complex use case

# pycallgraph3 = {version = "*", python = "^3.8"}
# pycallgraph2 = {version = "*", python = "<3.8"}

try:
    from pycallgraph3 import PyCallGraph
    from pycallgraph3.output import GraphvizOutput
except ImportError:
    from pycallgraph2 import PyCallGraph
    from pycallgraph2.output import GraphvizOutput

graphviz = GraphvizOutput()
graphviz.output_file = 'some_image_name.png'
with PyCallGraph(output=graphviz):
    from datetime import datetime
    time_str = datetime.now().strftime('%Y%m%d%H%M%S')
    filename = f'profile-{time_str}.png'
```

**Attached** Test File: [pycallgraph_test.py(.txt)](https://github.com/KyleKing/calcipy/files/6057892/pycallgraph_test.py.txt)

```py
# pyinstrument = "*"
from pyinstrument import Profiler
profiler = Profiler()
profiler.start()

# Code...

profiler.stop()
profiler.output_html(timeline=False)
profiler.open_in_browser(timeline=True)
logger.info('{profile}', profile=profiler.output_text(unicode=True, color=True, show_all=True))
logger.info('{profile}', profile=profiler.output_text(unicode=True, color=True, show_all=True, timeline=True))
```
