### ISSUE TITLE
Try out other optional dependencies

### ISSUE THREAD

**Issue by KyleKing** [KyleKing/calcipy#32]
- [x] [flake8-pie](https://github.com/sbdchd/flake8-pie): A flake8 extension that implements misc. lints 
- [x] [flake8-simplify](https://github.com/MartinThoma/flake8-simplify): make code simpler
- [x] [codecheck](https://github.com/yugabyte/codecheck): add as an alternative in README
- [x] [pylama](https://github.com/klen/pylama): add as an alternative in README
- [x] [flake8-annotations-complexity](https://github.com/best-doctor/flake8-annotations-complexity)
- [x] [flake8-variable-names](https://github.com/best-doctor/flake8-variables-names)
- [x] [flake8-typing-imports](https://github.com/asottile/flake8-typing-imports)
- [x] [flake8-type-checking](https://github.com/snok/flake8-type-checking) (more or less available in ruff not)
- [x] [import-linter](https://github.com/seddonym/import-linter) - write rules for how relative imports can be defined
- [x] [auto-all](https://github.com/jongracecox/auto-all): create `__all__` automatically for compliance with pyclean and to make a clean public interface
- [x] [mk](https://github.com/pycontribs/mk) helper for local developers/contributors
- [x] [flakeheaven](https://flakeheaven.readthedocs.io/en/latest/parsers.html) to lint code in markdown and other non-Python files
- [x] [Even more static formatters](https://github.com/life4/awesome-python-code-formatters)
- [ ] [Deal: Design by Contract](https://github.com/life4/deal)
- [x] [Slotscheck](https://github.com/ariebovenberg/slotscheck)
- [x] [Snug](https://github.com/ariebovenberg/snug): better requests testability {Really nice library, but using `pytest-responses` is sufficient}
- [x] [quacks](https://github.com/ariebovenberg/quacks): Protocol decorators {I don't have any use cases where this would be beneficial right now}
- [x] [pyta](https://github.com/pyta-uoft/pyta): add as an alternative in README (student-focused wrapper of pylint)
- [x] Use [munch](https://github.com/Infinidat/munch) instead of python-box because the initial structure can be defined with keyword arguments instead of a dict (note: not updated since a pre-release in 2020) > made `ddict` wrapper
- [x] ~[yesqa](https://github.com/asottile/yesqa) (Remove unnecessary noqa comments)~ {Removed H303 and other required noqa comments...}
- [x] [add-trailing-comma](https://pypi.org/project/add-trailing-comma/) (Added pre-commit hook)
- [x] [diff-cover](https://github.com/Bachmann1234/diff_cover) (Looks like it needs an XML output to check coverage)
    - See snippet below
- [x] pyupgrade (Setup git hook)
- [x] [rich](https://pypi.org/project/rich/) (Cool, but not needed)
- [x] [pydiatra](https://github.com/jwilk/pydiatra) - another static checker ~~but no release since 2019~~ (updated in 2021!) {Doesn't appear to have benefits beyond existing checkers with flake8}
- [x] [vulture](https://pypi.org/project/vulture/) (Finds dead code and respects noqa F401!). [Example](https://github.com/almazkun/gadd/blob/29bee5ef537fbfab995239edbfcbcc0577f9d523/gadd/gadd.py#L124-L154)
    - [x] [dead](https://github.com/asottile/dead) - returns more false positives because no way to raise minimum
- [x] [eradicate](https://github.com/myint/eradicate) finds commented-out code in Python files
- [x] [autoflake](https://pypi.org/project/autoflake/) (Removes missing imports)
    - [x] [pycln](https://pypi.org/project/pycln/) removes unused imports (more up to date than autoflake)
    - [x] Try [autoimport](https://github.com/lyz-code/autoimport/) {Mostly useful for Jupyter}
- [x] ~~Look at runtime [checking with pydantic](https://pydantic-docs.helpmanual.io/usage/validators/) ([/pydantic](https://github.com/samuelcolvin/pydantic))~~ (prefer TypeGuard from #28)
    - [x] [BearType](https://github.com/beartype/beartype) < Maybe prefer beartype, see [full example](https://github.com/beartype/beartype#industrial-example) and [cheat sheet](https://github.com/beartype/beartype#cheatsheet) (Closes #28)
- [x] ~[dodgy](https://github.com/landscapeio/dodgy) last release in 2019 unfortunately and landscape.io is 404~
- [x] See additional options used by [tidypy](https://github.com/jayclassless/tidypy#included-tools)
    - [x] [pyroma](https://pypi.org/project/pyroma/) - checks metadata in tar file, and surprisingly found errors. Adding to `nox`
        - `poetry run python -c "from pathlib import Path; from calcipy.file_helpers import delete_dir; delete_dir(Path('dist'))"`
        - `poetry build`
        - `poetry run pyroma dist/calcipy-0.2.0a0.tar.gz`
    - [ ] [check-wheel-contents](https://pypi.org/project/check-wheel-contents/)
- [x] Set flake8 min python version? Which package? (`--min-python-version=VERSION`)
- [x] [flake8-codes](https://pypi.org/project/flake8-codes/) -- finally, figure out which codes a flake8 plugin exposes!
- [x] [pylint](https://github.com/PyCQA/pylint/) (and the UML generator?)
- [x] [pydocstyle](https://github.com/PyCQA/pydocstyle/) (Implemented with flake8-docstrings)
    - [ ] [pycodestyle](https://pypi.org/project/pycodestyle/) previously pep8. Consider revisiting
- [x] [mccabe](https://github.com/PyCQA/mccabe) (In radon)
    - [x] and [wily](https://github.com/tonybaloney/wily)
- [x] [Inspector Tiger (`it`)](https://github.com/thg-consulting/it) - see snippet below
- [x] [Prospector](https://prospector.readthedocs.io/en/latest/index.html) - see snippet below (Recent releases, but not updated to latest isort)
- [x] [FHPythonUtils/SimpleSecurity](https://github.com/FHPythonUtils/SimpleSecurity) (Bundles bandit and others) and [semgrep rules](https://github.com/returntocorp/semgrep-rules) ([semgrep](https://pypi.org/project/semgrep/))
    - [x] [safety](https://github.com/pyupio/safety) (`poetry run safety check --full-report --cache --output insecure_report.json --json`) - created free account, but requires a `requirements.txt` file generated from poetry export. Note: to always run in a separate environment (Nox) to prevent malicious packages from clobbering methods
        - [x] See: https://github.com/pyupio/safety/issues/201#issuecomment-632627366 and https://github.com/pyupio/safety/issues/201#issuecomment-632671470
    - [x] [Dlint](https://github.com/duo-labs/dlint) is a tool for encouraging best coding practices and helping ensure we’re writing secure Python code
- [x] ~Try `Pyre-Check` ([pypi](https://pypi.org/project/pyre-check/)) even though it is *nix-only because it found a number of type errors possibly missed by pytype and mypy: [KyleKing/calcipy](https://console.muse.dev/result/KyleKing/calcipy/01F40N7A1JX1G5WSRPKBH1QR71) and [KyleKing/simple-crypt](https://console.muse.dev/result/KyleKing/simple-crypt/01F40N9714G10ERQV7GZR9SYEF)~ (non-Windows, so not worth messing with and the errors were for a number of false positives...)
- [x] Ensure that `pytype` and `mypy` are configured to be run as part of the test suite and possibly decide on one or the other (See #29)
    - [x] Consider [pytest-monkeytype](https://pypi.org/project/pytest-monkeytype/) (*Useful for legacy code bases, but not needed now*)
- [x] Checkout the dodo configuration file: https://pydoit.org/configuration.html
    - https://pydoit.org/extending.html (Example scaffold)
    - https://pydoit.org/extending.html#plugins
- [x] [Flake-8 Logging Format](https://github.com/globality-corp/flake8-logging-format)
- [x] [returns](https://github.com/dry-python/returns) - allows use of `@safe / @pipeline / Success / Failure` to make exception handling more explicit
- [x] [tryceratops](https://github.com/guilatrova/tryceratops) - flake8 linter for exception handling
    - [x] Add [linked guide on logging](https://guicommits.com/how-to-log-in-python-like-a-pro/)
- [x] [pip-audit](https://github.com/trailofbits/pip-audit) - audit 3rd party dependencies (use alongside safety?) {Removed because output dictionary would typically only error on pip}
- [x] Update alternatives: "There’s [prospector](https://github.com/landscapeio/prospector), [pylama](https://github.com/klen/pylama), [flake8](https://gitlab.com/pycqa/flake8), and ~~[ciocheck](https://github.com/ContinuumIO/ciocheck)~~ just to name a few" and [codecheck](https://pypi.org/project/codecheck/)

Related to ~#19~, ~#20~, ~#21~, #28, ~#29~, #31, #46, and [My-Programming-Sketchbook#11](https://github.com/KyleKing/My-Programming-Sketchbook/issues/11)

`pdbpp` notes:
- `?`: Help screen
- `s`: Step into a function/method
- `n`: Execute line and go to the next
- `c`: Continue (stop debugging and return to normal execution)
- `q`: Quit
- `sticky`: pin pdb output alongsid
- `p <var name>`: Print (or `pp ...`)
- `\`: value of all variables in scope

See: https://www.digitalocean.com/community/tutorials/how-to-use-the-python-debugger and https://kapeli.com/cheat_sheets/Python_Debugger.docset/Contents/Resources/Documents/index

---

FYI: Below is a list of dependencies removed in https://github.com/KyleKing/calcipy/pull/34/commits/f052954c9c9dbc6e24a0bace1bd16190da0298d3

```toml
MonkeyType = "*"
pyannotate = "*"
pycallgraph3 = "*"
rich = "*"

# Explanantions
gitchangelog = "*"  # Replaced with commitizen
lxml = "*"  # Needed for gitchangelog
yesqa = "*"  # Causes issues
```
