### ISSUE TITLE
Check that enable/disable works as expected

### ISSUE THREAD

**Issue by KyleKing** [KyleKing/calcipy#9]
- [X] ~Follows #6~
- [X] ~Try out `poetry add dephell -D` `dephell project register --from=pyproject.toml ~/Developer/dash_dev` ([source](https://github.com/python-poetry/poetry/issues/34#issuecomment-726013631)) to check that dash_charts can add loggers without dash_dev logs appearing~
    - [DepHell docs](https://dephell.readthedocs.io/cmd-project-register.html)
- [X] Check loguru issues like this one for examples https://github.com/Delgan/loguru/issues/297
- [X] Update, the regular `path` should just work. See [comment](https://github.com/python-poetry/poetry/issues/1168#issuecomment-714777590) and [repo example](https://github.com/sinoroc/foosball)

**Comment by sinoroc** [comment]
As far as I understood it, it should be `dephell project register --from=pyproject ~/Developer/dash_dev`. The _from_ argument should be a project type, in that case the format would be `pyproject`. There is also a `poetry` format, but somehow it behaved strange in my quick test.

* https://dephell.readthedocs.io/cmd-deps-convert.html#supported-formats

**Comment by KyleKing** [comment]
Implemented demo in https://github.com/KyleKing/calcipy/tree/examples/loguru-toggle
